[package]
name = "edgeware-rpc"
version = "3.2.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
description = "Edgeware rpc"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpc-core = "15.0.0"
jsonrpc-pubsub = "15.0.0"
edgeware-primitives = { path = "../primitives" }
edgeware-runtime = { path = "../runtime" }
pallet-contracts-rpc = {  git = "https://github.com/woozzzzy/substrate", branch = "bb" }
pallet-transaction-payment-rpc = { git = "https://github.com/woozzzzy/substrate", branch = "bb" }
sc-client-api = { git = "https://github.com/woozzzzy/substrate", branch = "bb" }
sc-consensus-aura = {  git = "https://github.com/woozzzzy/substrate", branch = "bb" }
sc-consensus-epochs = {  git = "https://github.com/woozzzzy/substrate", branch = "bb" }
sc-finality-grandpa = {  git = "https://github.com/woozzzzy/substrate", branch = "bb" }
sc-finality-grandpa-rpc = {  git = "https://github.com/woozzzzy/substrate", branch = "bb" }
sc-keystore = { git = "https://github.com/woozzzzy/substrate", branch = "bb" }
sc-network = {  git = "https://github.com/woozzzzy/substrate", branch = "bb" }
sc-rpc-api = {  git = "https://github.com/woozzzzy/substrate", branch = "bb" }
sc-rpc = { git = "https://github.com/woozzzzy/substrate", branch = "bb" }
sp-api = { git = "https://github.com/woozzzzy/substrate", branch = "bb" }
sp-block-builder = { git = "https://github.com/woozzzzy/substrate", branch = "bb" }
sp-blockchain = { git = "https://github.com/woozzzzy/substrate", branch = "bb" }
sp-consensus = {  git = "https://github.com/woozzzzy/substrate", branch = "bb" }
sp-consensus-aura = {  git = "https://github.com/woozzzzy/substrate", branch = "bb" }
sp-runtime = { git = "https://github.com/woozzzzy/substrate", branch = "bb" }
sp-transaction-pool = { git = "https://github.com/woozzzzy/substrate", branch = "bb" }
substrate-frame-rpc-system = { git = "https://github.com/woozzzzy/substrate", branch = "bb" }
pallet-ethereum = { git = "https://github.com/woozzzzy/frontier", branch = "bb" }
fc-rpc = { git = "https://github.com/woozzzzy/frontier", branch = "bb", features = ["rpc_binary_search_estimate"] }
fc-rpc-core = { git = "https://github.com/woozzzzy/frontier", branch = "bb" }
