[package]
name = "edgeware-executor"
version = "3.2.0"
authors = ["Commonwealth Labs <hello@commonwealth.im>"]
description = "Edgeware implementation using a substrate node."
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
trie-root = "0.16.0"
codec = { package = "parity-scale-codec", version = "1.3.0" }
sp-io = { git = "https://github.com/woozzzzy/substrate", branch = "polkadot-v0.9.10"}
sp-state-machine = { git = "https://github.com/woozzzzy/substrate", branch = "polkadot-v0.9.10"}
sc-executor = { git = "https://github.com/woozzzzy/substrate", branch = "polkadot-v0.9.10" }
sp-core = { git = "https://github.com/woozzzzy/substrate", branch = "polkadot-v0.9.10"}
sp-trie = { git = "https://github.com/woozzzzy/substrate", branch = "polkadot-v0.9.10"}
frame-benchmarking = { git = "https://github.com/woozzzzy/substrate", branch = "polkadot-v0.9.10"}

edgeware-primitives = { version = "3.2.0", path = "../primitives" }
edgeware-runtime = { version = "3.2.0", path = "../runtime" }
edgeware-runtime-interface = { version = "3.2.0", path = "../runtime-interface" }

[dev-dependencies]
sp-runtime = { git = "https://github.com/woozzzzy/substrate", branch = "polkadot-v0.9.10"}
frame-support = { git = "https://github.com/woozzzzy/substrate", branch = "polkadot-v0.9.10"}
pallet-balances = { git = "https://github.com/woozzzzy/substrate", branch = "polkadot-v0.9.10"}
pallet-transaction-payment = { git = "https://github.com/woozzzzy/substrate", branch = "polkadot-v0.9.10"}
pallet-session = { git = "https://github.com/woozzzzy/substrate", branch = "polkadot-v0.9.10"}
frame-system = { git = "https://github.com/woozzzzy/substrate", branch = "polkadot-v0.9.10"}
pallet-timestamp = { git = "https://github.com/woozzzzy/substrate", branch = "polkadot-v0.9.10"}
pallet-treasury = { git = "https://github.com/woozzzzy/substrate", branch = "polkadot-v0.9.10"}
pallet-grandpa = { git = "https://github.com/woozzzzy/substrate", branch = "polkadot-v0.9.10"}
pallet-indices = { git = "https://github.com/woozzzzy/substrate", branch = "polkadot-v0.9.10"}
wabt = "0.10.0"
criterion = "0.3.0"

[features]
wasmtime = [
    "sc-executor/wasmtime",
]
wasmi-errno = [
    "sc-executor/wasmi-errno",
]
stress-test = []

[[bench]]
name = "bench"
harness = false
